apiVersion: v1
kind: Pod
metadata:
  name: melt
  labels:
    app: melt
spec:
  containers:
  - image: robinhoodis/melt:latest
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: Always
    name: melt
  restartPolicy: Always
